#include "memory/memory.hpp"

#define PATTERN_TABLES_START 0x0000
#define PATTERN_TABLES_END 0x1FFF

#define NAME_TABLES_START 0x2000
#define NAME_TABLES_END 0x3EFF
#define NAME_TABLES_MIRROR_SRC_START 0x2000
#define NAME_TABLES_MIRROR_SRC_END 0x2EFF
#define NAME_TABLES_MIRROR_DST_START 0x3000
#define NAME_TABLES_MIRROR_DST_END 0x3EFF

#define PALETTES_START 0x3F00
#define PALETTES_END 0x3FFF
#define PALETTES_MIRROR_SRC_START 0x3F00
#define PALETTES_MIRROR_SRC_END 0x3F1F
#define PALETTES_MIRROR_DST_START 0x3F20
#define PALETTES_MIRROR_DST_END 0x3FFF

class VRAM : public Memory {
  class PatternTables : public Section {

  };
};
